-- Users テーブル作成
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  first_name_kana VARCHAR(100),
  last_name_kana VARCHAR(100),
  gender VARCHAR(10),
  birthdate DATE,
  address TEXT,
  phone_number VARCHAR(20),
  role TINYINT NOT NULL DEFAULT 4 COMMENT '1:super_admin, 2:admin, 3:manager, 4:employee',
  default_role TINYINT NULL COMMENT 'ユーザーのデフォルトロール（1:super_admin, 2:admin, 3:manager, 4:employee）',
  follow_up_required BOOLEAN DEFAULT FALSE COMMENT 'フォローアップ必要フラグ',
  follow_up_reason TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'フォローアップ理由',
  last_follow_up_date DATE COMMENT '最終フォローアップ日',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  INDEX idx_users_role (role),
  INDEX idx_users_default_role (default_role),
  INDEX idx_users_follow_up_required (follow_up_required),
  INDEX idx_users_last_follow_up_date (last_follow_up_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 