-- 営業活動管理テーブルの作成
CREATE TABLE IF NOT EXISTS sales_activities (
  id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci PRIMARY KEY,
  client_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '取引先ID',
  project_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '関連案件ID',
  activity_type ENUM('new_proposal', 'extension', 'upsell', 'replacement', 'other') NOT NULL COMMENT '活動タイプ',
  target_user_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '対象エンジニアID',
  sales_rep_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '担当営業ID',
  status ENUM('planning', 'proposed', 'negotiating', 'won', 'lost', 'on_hold') DEFAULT 'planning' COMMENT 'ステータス',
  probability INT DEFAULT 0 COMMENT '成約確率（%）',
  estimated_monthly_amount DECIMAL(10, 2) COMMENT '予想月額',
  estimated_start_date DATE COMMENT '予想開始日',
  next_action VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '次回アクション',
  next_action_date DATE COMMENT '次回アクション日',
  notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'メモ',
  lost_reason VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '失注理由',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '作成日時',
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新日時',
  deleted_at DATETIME(3) NULL COMMENT '削除日時',
  CONSTRAINT fk_sales_activities_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_sales_activities_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_sales_activities_user FOREIGN KEY (target_user_id) REFERENCES users(id),
  CONSTRAINT fk_sales_activities_sales_rep FOREIGN KEY (sales_rep_id) REFERENCES users(id),
  INDEX idx_sales_activities_status (status),
  INDEX idx_sales_activities_next_action (next_action_date),
  INDEX idx_sales_activities_client_id (client_id),
  INDEX idx_sales_activities_target_user_id (target_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='営業活動管理テーブル';