-- アラート履歴テーブル
CREATE TABLE IF NOT EXISTS `alert_histories` (
    `id` VARCHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    `alert_setting_id` VARCHAR(36) NOT NULL COMMENT 'アラート設定ID',
    `user_id` VARCHAR(36) NOT NULL COMMENT '対象ユーザーID',
    `weekly_report_id` VARCHAR(36) COMMENT '関連する週報ID',
    `alert_type` ENUM('overwork', 'work_hours_change', 'consecutive_holiday_work', 'monthly_overtime', 'unsubmitted') NOT NULL COMMENT 'アラートタイプ',
    `severity` ENUM('low', 'medium', 'high') NOT NULL COMMENT '重要度',
    `detected_value` DECIMAL(10,2) NOT NULL COMMENT '検出値',
    `threshold_value` DECIMAL(10,2) NOT NULL COMMENT '閾値',
    `message` TEXT NOT NULL COMMENT 'アラートメッセージ',
    `metadata` JSON COMMENT '追加情報（週報期間、前週比較データ等）',
    `status` ENUM('unhandled', 'handling', 'resolved', 'ignored') NOT NULL DEFAULT 'unhandled' COMMENT 'アラートステータス',
    `handled_by` VARCHAR(36) COMMENT '対応者ID',
    `handled_at` TIMESTAMP NULL COMMENT '対応日時',
    `resolution_comment` TEXT COMMENT '対応コメント',
    `notification_sent` BOOLEAN NOT NULL DEFAULT FALSE COMMENT '通知送信済みフラグ',
    `notification_sent_at` TIMESTAMP NULL COMMENT '通知送信日時',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    KEY `idx_alert_histories_setting` (`alert_setting_id`),
    KEY `idx_alert_histories_user` (`user_id`),
    KEY `idx_alert_histories_report` (`weekly_report_id`),
    KEY `idx_alert_histories_type` (`alert_type`),
    KEY `idx_alert_histories_status` (`status`),
    KEY `idx_alert_histories_severity` (`severity`),
    KEY `idx_alert_histories_created` (`created_at`),
    KEY `idx_alert_histories_user_status` (`user_id`, `status`),
    KEY `idx_alert_histories_type_status_created` (`alert_type`, `status`, `created_at`),
    
    CONSTRAINT `fk_alert_histories_setting` FOREIGN KEY (`alert_setting_id`) REFERENCES `alert_settings` (`id`),
    CONSTRAINT `fk_alert_histories_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_alert_histories_report` FOREIGN KEY (`weekly_report_id`) REFERENCES `weekly_reports` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_alert_histories_handled_by` FOREIGN KEY (`handled_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='アラート履歴テーブル';