-- 技術マスタのシードデータ投入

-- プログラミング言語 (programming_languages)
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES
(UUID(), 'programming_languages', 'java', 'Java', 'java', 'オブジェクト指向プログラミング言語', 0, true, 1),
(UUID(), 'programming_languages', 'javascript', 'JavaScript', 'js,javascript,ES6,ES2015', 'Web開発用スクリプト言語', 0, true, 2),
(UUID(), 'programming_languages', 'typescript', 'TypeScript', 'ts,typescript', 'JavaScriptの型付きスーパーセット', 0, true, 3),
(UUID(), 'programming_languages', 'python', 'Python', 'python,py', '汎用高水準プログラミング言語', 0, true, 4),
(UUID(), 'programming_languages', 'go', 'Go', 'golang,go', 'Google開発のプログラミング言語', 0, true, 5),
(UUID(), 'programming_languages', 'csharp', 'C#', 'c#,cs,csharp', 'Microsoft開発のオブジェクト指向言語', 0, true, 6),
(UUID(), 'programming_languages', 'php', 'PHP', 'php', 'サーバーサイドスクリプト言語', 0, true, 7),
(UUID(), 'programming_languages', 'ruby', 'Ruby', 'ruby,rb', 'オブジェクト指向スクリプト言語', 0, true, 8),
(UUID(), 'programming_languages', 'swift', 'Swift', 'swift', 'Apple開発のプログラミング言語', 0, true, 9),
(UUID(), 'programming_languages', 'kotlin', 'Kotlin', 'kotlin,kt', 'JVM上で動作する静的型付け言語', 0, true, 10),
(UUID(), 'programming_languages', 'rust', 'Rust', 'rust,rs', 'システムプログラミング言語', 0, true, 11),
(UUID(), 'programming_languages', 'cplusplus', 'C++', 'c++,cpp,cxx', 'オブジェクト指向プログラミング言語', 0, true, 12),
(UUID(), 'programming_languages', 'c', 'C', 'c', 'システムプログラミング言語', 0, true, 13),
(UUID(), 'programming_languages', 'scala', 'Scala', 'scala', 'JVM上で動作する関数型言語', 0, true, 14),
(UUID(), 'programming_languages', 'dart', 'Dart', 'dart', 'Google開発のプログラミング言語', 0, true, 15),
(UUID(), 'programming_languages', 'r', 'R', 'r,rlang', '統計解析向けプログラミング言語', 0, true, 16),
(UUID(), 'programming_languages', 'matlab', 'MATLAB', 'matlab', '数値計算プログラミング言語', 0, true, 17),
(UUID(), 'programming_languages', 'perl', 'Perl', 'perl,pl', 'テキスト処理に優れた言語', 0, true, 18),
(UUID(), 'programming_languages', 'elixir', 'Elixir', 'elixir,ex', 'Erlang VM上で動作する関数型言語', 0, true, 19),
(UUID(), 'programming_languages', 'clojure', 'Clojure', 'clojure,clj', 'JVM上で動作するLisp系言語', 0, true, 20),
(UUID(), 'programming_languages', 'haskell', 'Haskell', 'haskell,hs', '純粋関数型プログラミング言語', 0, true, 21),
(UUID(), 'programming_languages', 'lua', 'Lua', 'lua', '軽量スクリプト言語', 0, true, 22),
(UUID(), 'programming_languages', 'julia', 'Julia', 'julia,jl', '科学技術計算向け言語', 0, true, 23),
(UUID(), 'programming_languages', 'groovy', 'Groovy', 'groovy', 'JVM上で動作する動的言語', 0, true, 24),
(UUID(), 'programming_languages', 'objective-c', 'Objective-C', 'objc,objective-c', 'Apple製品開発言語', 0, true, 25),
(UUID(), 'programming_languages', 'vb.net', 'VB.NET', 'vb,vb.net,visualbasic', 'Visual Basic .NET', 0, true, 26),
(UUID(), 'programming_languages', 'fsharp', 'F#', 'f#,fsharp,fs', '.NET向け関数型言語', 0, true, 27),
(UUID(), 'programming_languages', 'erlang', 'Erlang', 'erlang,erl', '並行処理向け関数型言語', 0, true, 28),
(UUID(), 'programming_languages', 'shell', 'Shell Script', 'shell,bash,sh,zsh', 'シェルスクリプト', 0, true, 29),
(UUID(), 'programming_languages', 'powershell', 'PowerShell', 'powershell,ps1', 'Windows向けシェル', 0, true, 30),
(UUID(), 'programming_languages', 'assembly', 'Assembly', 'asm,assembly', 'アセンブリ言語', 0, true, 31),
(UUID(), 'programming_languages', 'cobol', 'COBOL', 'cobol', '事務処理向け言語', 0, true, 32),
(UUID(), 'programming_languages', 'fortran', 'Fortran', 'fortran', '科学技術計算言語', 0, true, 33),
(UUID(), 'programming_languages', 'pascal', 'Pascal', 'pascal', '教育用プログラミング言語', 0, true, 34),
(UUID(), 'programming_languages', 'ada', 'Ada', 'ada', '高信頼性システム向け言語', 0, true, 35),
(UUID(), 'programming_languages', 'lisp', 'Lisp', 'lisp', 'リスト処理言語', 0, true, 36),
(UUID(), 'programming_languages', 'scheme', 'Scheme', 'scheme,scm', 'Lisp方言', 0, true, 37),
(UUID(), 'programming_languages', 'ocaml', 'OCaml', 'ocaml,ml', '関数型プログラミング言語', 0, true, 38),
(UUID(), 'programming_languages', 'racket', 'Racket', 'racket,rkt', 'Scheme系言語', 0, true, 39),
(UUID(), 'programming_languages', 'nim', 'Nim', 'nim', 'システムプログラミング言語', 0, true, 40),
(UUID(), 'programming_languages', 'crystal', 'Crystal', 'crystal,cr', 'Ruby風静的型付け言語', 0, true, 41),
(UUID(), 'programming_languages', 'zig', 'Zig', 'zig', 'システムプログラミング言語', 0, true, 42),
(UUID(), 'programming_languages', 'd', 'D', 'd,dlang', 'システムプログラミング言語', 0, true, 43),
(UUID(), 'programming_languages', 'solidity', 'Solidity', 'solidity,sol', 'スマートコントラクト言語', 0, true, 44),
(UUID(), 'programming_languages', 'vyper', 'Vyper', 'vyper,vy', 'Python風スマートコントラクト言語', 0, true, 45),
(UUID(), 'programming_languages', 'apex', 'Apex', 'apex', 'Salesforce開発言語', 0, true, 46),
(UUID(), 'programming_languages', 'abap', 'ABAP', 'abap', 'SAP開発言語', 0, true, 47),
(UUID(), 'programming_languages', 'pl-sql', 'PL/SQL', 'plsql,pl/sql', 'Oracle手続き型言語', 0, true, 48),
(UUID(), 'programming_languages', 't-sql', 'T-SQL', 'tsql,t-sql', 'Microsoft SQL Server言語', 0, true, 49),
(UUID(), 'programming_languages', 'sas', 'SAS', 'sas', '統計解析システム言語', 0, true, 50),
(UUID(), 'programming_languages', 'vhdl', 'VHDL', 'vhdl', 'ハードウェア記述言語', 0, true, 51),
(UUID(), 'programming_languages', 'verilog', 'Verilog', 'verilog', 'ハードウェア記述言語', 0, true, 52),
(UUID(), 'programming_languages', 'hack', 'Hack', 'hack', 'Facebook開発のPHP方言', 0, true, 53),
(UUID(), 'programming_languages', 'elm', 'Elm', 'elm', 'Web向け関数型言語', 0, true, 54),
(UUID(), 'programming_languages', 'purescript', 'PureScript', 'purescript,purs', 'Haskell風JavaScript代替', 0, true, 55),
(UUID(), 'programming_languages', 'reasonml', 'ReasonML', 'reason,reasonml', 'OCaml構文のJavaScript', 0, true, 56),
(UUID(), 'programming_languages', 'coffeescript', 'CoffeeScript', 'coffee,coffeescript', 'JavaScript代替言語', 0, true, 57),
(UUID(), 'programming_languages', 'livescript', 'LiveScript', 'livescript,ls', 'JavaScript代替言語', 0, true, 58),
(UUID(), 'programming_languages', 'actionscript', 'ActionScript', 'as,actionscript', 'Flash開発言語', 0, true, 59),
(UUID(), 'programming_languages', 'haxe', 'Haxe', 'haxe,hx', 'マルチプラットフォーム言語', 0, true, 60),
(UUID(), 'programming_languages', 'tcl', 'Tcl', 'tcl', 'ツールコマンド言語', 0, true, 61),
(UUID(), 'programming_languages', 'awk', 'AWK', 'awk', 'テキスト処理言語', 0, true, 62),
(UUID(), 'programming_languages', 'sed', 'sed', 'sed', 'ストリームエディタ', 0, true, 63),
(UUID(), 'programming_languages', 'prolog', 'Prolog', 'prolog', '論理プログラミング言語', 0, true, 64),
(UUID(), 'programming_languages', 'smalltalk', 'Smalltalk', 'smalltalk,st', 'オブジェクト指向言語', 0, true, 65),
(UUID(), 'programming_languages', 'forth', 'Forth', 'forth', 'スタック指向言語', 0, true, 66),
(UUID(), 'programming_languages', 'j', 'J', 'j,jlang', 'APL系配列言語', 0, true, 67),
(UUID(), 'programming_languages', 'apl', 'APL', 'apl', '配列プログラミング言語', 0, true, 68),
(UUID(), 'programming_languages', 'k', 'K', 'k,klang', 'APL系配列言語', 0, true, 69),
(UUID(), 'programming_languages', 'q', 'Q', 'q,qlang,kdb+', '金融向けデータベース言語', 0, true, 70),
(UUID(), 'programming_languages', 'io', 'Io', 'io,iolang', 'プロトタイプベース言語', 0, true, 71),
(UUID(), 'programming_languages', 'factor', 'Factor', 'factor', 'スタック指向言語', 0, true, 72),
(UUID(), 'programming_languages', 'red', 'Red', 'red', 'フルスタック言語', 0, true, 73),
(UUID(), 'programming_languages', 'raku', 'Raku', 'raku,perl6', 'Perl 6の新名称', 0, true, 74),
(UUID(), 'programming_languages', 'ballerina', 'Ballerina', 'ballerina,bal', 'クラウドネイティブ言語', 0, true, 75),
(UUID(), 'programming_languages', 'v', 'V', 'v,vlang', 'シンプルな言語', 0, true, 76),
(UUID(), 'programming_languages', 'pony', 'Pony', 'pony', 'アクターモデル言語', 0, true, 77),
(UUID(), 'programming_languages', 'chapel', 'Chapel', 'chapel,chpl', '並列プログラミング言語', 0, true, 78),
(UUID(), 'programming_languages', 'x10', 'X10', 'x10', '並列プログラミング言語', 0, true, 79),
(UUID(), 'programming_languages', 'idris', 'Idris', 'idris,idr', '依存型プログラミング言語', 0, true, 80),
(UUID(), 'programming_languages', 'agda', 'Agda', 'agda', '依存型プログラミング言語', 0, true, 81),
(UUID(), 'programming_languages', 'coq', 'Coq', 'coq', '証明支援システム', 0, true, 82),
(UUID(), 'programming_languages', 'lean', 'Lean', 'lean', '証明支援システム', 0, true, 83),
(UUID(), 'programming_languages', 'isabelle', 'Isabelle', 'isabelle', '証明支援システム', 0, true, 84),
(UUID(), 'programming_languages', 'mercury', 'Mercury', 'mercury', '論理関数型言語', 0, true, 85),
(UUID(), 'programming_languages', 'curry', 'Curry', 'curry', '関数論理プログラミング言語', 0, true, 86),
(UUID(), 'programming_languages', 'clean', 'Clean', 'clean', '純粋関数型言語', 0, true, 87),
(UUID(), 'programming_languages', 'miranda', 'Miranda', 'miranda', '関数型プログラミング言語', 0, true, 88),
(UUID(), 'programming_languages', 'sml', 'Standard ML', 'sml,ml', '関数型プログラミング言語', 0, true, 89),
(UUID(), 'programming_languages', 'eiffel', 'Eiffel', 'eiffel', 'オブジェクト指向言語', 0, true, 90),
(UUID(), 'programming_languages', 'modula-2', 'Modula-2', 'modula2', 'システムプログラミング言語', 0, true, 91),
(UUID(), 'programming_languages', 'modula-3', 'Modula-3', 'modula3', 'システムプログラミング言語', 0, true, 92),
(UUID(), 'programming_languages', 'oberon', 'Oberon', 'oberon', 'システムプログラミング言語', 0, true, 93),
(UUID(), 'programming_languages', 'simula', 'Simula', 'simula', '最初のオブジェクト指向言語', 0, true, 94),
(UUID(), 'programming_languages', 'algol', 'ALGOL', 'algol', 'アルゴリズム記述言語', 0, true, 95),
(UUID(), 'programming_languages', 'basic', 'BASIC', 'basic', '初心者向け言語', 0, true, 96),
(UUID(), 'programming_languages', 'logo', 'Logo', 'logo', '教育用プログラミング言語', 0, true, 97),
(UUID(), 'programming_languages', 'scratch', 'Scratch', 'scratch', 'ビジュアルプログラミング言語', 0, true, 98),
(UUID(), 'programming_languages', 'blockly', 'Blockly', 'blockly', 'ビジュアルプログラミング言語', 0, true, 99),
(UUID(), 'programming_languages', 'labview', 'LabVIEW', 'labview', 'グラフィカルプログラミング言語', 0, true, 100);

-- サーバー・データベース (servers_databases)
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES
(UUID(), 'servers_databases', 'mysql', 'MySQL', 'mysql', 'オープンソースRDBMS', 0, true, 1),
(UUID(), 'servers_databases', 'postgresql', 'PostgreSQL', 'postgres,postgresql,pg', 'オープンソースRDBMS', 0, true, 2),
(UUID(), 'servers_databases', 'mariadb', 'MariaDB', 'mariadb', 'MySQLフォーク', 0, true, 3),
(UUID(), 'servers_databases', 'oracle', 'Oracle Database', 'oracle,oracledb', '商用RDBMS', 0, true, 4),
(UUID(), 'servers_databases', 'sqlserver', 'SQL Server', 'mssql,sqlserver,sql server', 'Microsoft RDBMS', 0, true, 5),
(UUID(), 'servers_databases', 'mongodb', 'MongoDB', 'mongo,mongodb', 'ドキュメント指向DB', 0, true, 6),
(UUID(), 'servers_databases', 'redis', 'Redis', 'redis', 'インメモリDB', 0, true, 7),
(UUID(), 'servers_databases', 'elasticsearch', 'Elasticsearch', 'elasticsearch,es', '全文検索エンジン', 0, true, 8),
(UUID(), 'servers_databases', 'cassandra', 'Apache Cassandra', 'cassandra', '分散型NoSQL', 0, true, 9),
(UUID(), 'servers_databases', 'dynamodb', 'Amazon DynamoDB', 'dynamodb', 'AWS NoSQL', 0, true, 10),
(UUID(), 'servers_databases', 'firebase', 'Firebase', 'firebase', 'Google BaaS', 0, true, 11),
(UUID(), 'servers_databases', 'couchdb', 'CouchDB', 'couchdb', 'ドキュメント指向DB', 0, true, 12),
(UUID(), 'servers_databases', 'neo4j', 'Neo4j', 'neo4j', 'グラフDB', 0, true, 13),
(UUID(), 'servers_databases', 'influxdb', 'InfluxDB', 'influxdb', '時系列DB', 0, true, 14),
(UUID(), 'servers_databases', 'memcached', 'Memcached', 'memcached', 'キャッシュサーバー', 0, true, 15),
(UUID(), 'servers_databases', 'hbase', 'HBase', 'hbase', 'Hadoop DB', 0, true, 16),
(UUID(), 'servers_databases', 'couchbase', 'Couchbase', 'couchbase', 'NoSQL DB', 0, true, 17),
(UUID(), 'servers_databases', 'riak', 'Riak', 'riak', '分散型DB', 0, true, 18),
(UUID(), 'servers_databases', 'arangodb', 'ArangoDB', 'arangodb', 'マルチモデルDB', 0, true, 19),
(UUID(), 'servers_databases', 'orientdb', 'OrientDB', 'orientdb', 'マルチモデルDB', 0, true, 20),
(UUID(), 'servers_databases', 'apache', 'Apache HTTP Server', 'apache,httpd', 'Webサーバー', 0, true, 21),
(UUID(), 'servers_databases', 'nginx', 'Nginx', 'nginx', 'Webサーバー', 0, true, 22),
(UUID(), 'servers_databases', 'iis', 'IIS', 'iis', 'Microsoft Webサーバー', 0, true, 23),
(UUID(), 'servers_databases', 'tomcat', 'Apache Tomcat', 'tomcat', 'Javaサーブレットコンテナ', 0, true, 24),
(UUID(), 'servers_databases', 'jetty', 'Jetty', 'jetty', 'Javaサーブレットコンテナ', 0, true, 25),
(UUID(), 'servers_databases', 'wildfly', 'WildFly', 'wildfly,jboss', 'Java EEサーバー', 0, true, 26),
(UUID(), 'servers_databases', 'weblogic', 'WebLogic', 'weblogic', 'Oracle Java EEサーバー', 0, true, 27),
(UUID(), 'servers_databases', 'websphere', 'WebSphere', 'websphere', 'IBM Java EEサーバー', 0, true, 28),
(UUID(), 'servers_databases', 'glassfish', 'GlassFish', 'glassfish', 'Java EEサーバー', 0, true, 29),
(UUID(), 'servers_databases', 'nodejs', 'Node.js', 'node,nodejs,node.js', 'JavaScript実行環境', 0, true, 30),
(UUID(), 'servers_databases', 'deno', 'Deno', 'deno', 'JavaScript/TypeScript実行環境', 0, true, 31),
(UUID(), 'servers_databases', 'bun', 'Bun', 'bun', 'JavaScript実行環境', 0, true, 32),
(UUID(), 'servers_databases', 'rabbitmq', 'RabbitMQ', 'rabbitmq', 'メッセージブローカー', 0, true, 33),
(UUID(), 'servers_databases', 'kafka', 'Apache Kafka', 'kafka', 'メッセージブローカー', 0, true, 34),
(UUID(), 'servers_databases', 'activemq', 'ActiveMQ', 'activemq', 'メッセージブローカー', 0, true, 35),
(UUID(), 'servers_databases', 'zeromq', 'ZeroMQ', 'zeromq,zmq', 'メッセージングライブラリ', 0, true, 36),
(UUID(), 'servers_databases', 'mqtt', 'MQTT', 'mqtt', 'IoTプロトコル', 0, true, 37),
(UUID(), 'servers_databases', 'nats', 'NATS', 'nats', 'メッセージングシステム', 0, true, 38),
(UUID(), 'servers_databases', 'pulsar', 'Apache Pulsar', 'pulsar', 'メッセージングシステム', 0, true, 39),
(UUID(), 'servers_databases', 'solr', 'Apache Solr', 'solr', '検索プラットフォーム', 0, true, 40),
(UUID(), 'servers_databases', 'lucene', 'Apache Lucene', 'lucene', '検索エンジンライブラリ', 0, true, 41),
(UUID(), 'servers_databases', 'haproxy', 'HAProxy', 'haproxy', 'ロードバランサー', 0, true, 42),
(UUID(), 'servers_databases', 'varnish', 'Varnish', 'varnish', 'HTTPアクセラレータ', 0, true, 43),
(UUID(), 'servers_databases', 'squid', 'Squid', 'squid', 'プロキシサーバー', 0, true, 44),
(UUID(), 'servers_databases', 'lighttpd', 'Lighttpd', 'lighttpd', '軽量Webサーバー', 0, true, 45),
(UUID(), 'servers_databases', 'caddy', 'Caddy', 'caddy', 'Webサーバー', 0, true, 46),
(UUID(), 'servers_databases', 'traefik', 'Traefik', 'traefik', 'リバースプロキシ', 0, true, 47),
(UUID(), 'servers_databases', 'consul', 'Consul', 'consul', 'サービスメッシュ', 0, true, 48),
(UUID(), 'servers_databases', 'etcd', 'etcd', 'etcd', '分散KVストア', 0, true, 49),
(UUID(), 'servers_databases', 'zookeeper', 'Apache ZooKeeper', 'zookeeper', '分散コーディネーション', 0, true, 50);

-- ツール (tools)  
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES
(UUID(), 'tools', 'git', 'Git', 'git', 'バージョン管理システム', 0, true, 1),
(UUID(), 'tools', 'svn', 'Subversion', 'svn,subversion', 'バージョン管理システム', 0, true, 2),
(UUID(), 'tools', 'mercurial', 'Mercurial', 'hg,mercurial', 'バージョン管理システム', 0, true, 3),
(UUID(), 'tools', 'docker', 'Docker', 'docker', 'コンテナプラットフォーム', 0, true, 4),
(UUID(), 'tools', 'kubernetes', 'Kubernetes', 'k8s,kubernetes', 'コンテナオーケストレーション', 0, true, 5),
(UUID(), 'tools', 'jenkins', 'Jenkins', 'jenkins', 'CI/CDツール', 0, true, 6),
(UUID(), 'tools', 'gitlab', 'GitLab', 'gitlab', 'DevOpsプラットフォーム', 0, true, 7),
(UUID(), 'tools', 'github', 'GitHub', 'github', 'コード共有プラットフォーム', 0, true, 8),
(UUID(), 'tools', 'bitbucket', 'Bitbucket', 'bitbucket', 'Gitリポジトリ管理', 0, true, 9),
(UUID(), 'tools', 'circleci', 'CircleCI', 'circleci', 'CI/CDツール', 0, true, 10),
(UUID(), 'tools', 'travisci', 'Travis CI', 'travis,travisci', 'CI/CDツール', 0, true, 11),
(UUID(), 'tools', 'githubactions', 'GitHub Actions', 'github actions,actions', 'CI/CDツール', 0, true, 12),
(UUID(), 'tools', 'ansible', 'Ansible', 'ansible', '構成管理ツール', 0, true, 13),
(UUID(), 'tools', 'terraform', 'Terraform', 'terraform', 'IaCツール', 0, true, 14),
(UUID(), 'tools', 'puppet', 'Puppet', 'puppet', '構成管理ツール', 0, true, 15),
(UUID(), 'tools', 'chef', 'Chef', 'chef', '構成管理ツール', 0, true, 16),
(UUID(), 'tools', 'saltstack', 'SaltStack', 'salt,saltstack', '構成管理ツール', 0, true, 17),
(UUID(), 'tools', 'vagrant', 'Vagrant', 'vagrant', '開発環境構築ツール', 0, true, 18),
(UUID(), 'tools', 'packer', 'Packer', 'packer', 'イメージ作成ツール', 0, true, 19),
(UUID(), 'tools', 'prometheus', 'Prometheus', 'prometheus', '監視システム', 0, true, 20),
(UUID(), 'tools', 'grafana', 'Grafana', 'grafana', '可視化ツール', 0, true, 21),
(UUID(), 'tools', 'nagios', 'Nagios', 'nagios', '監視システム', 0, true, 22),
(UUID(), 'tools', 'zabbix', 'Zabbix', 'zabbix', '監視システム', 0, true, 23),
(UUID(), 'tools', 'datadog', 'Datadog', 'datadog', '監視サービス', 0, true, 24),
(UUID(), 'tools', 'newrelic', 'New Relic', 'newrelic,new relic', 'APMツール', 0, true, 25),
(UUID(), 'tools', 'splunk', 'Splunk', 'splunk', 'ログ分析ツール', 0, true, 26),
(UUID(), 'tools', 'elk', 'ELK Stack', 'elk,elastic stack', 'ログ分析スタック', 0, true, 27),
(UUID(), 'tools', 'logstash', 'Logstash', 'logstash', 'ログ収集ツール', 0, true, 28),
(UUID(), 'tools', 'kibana', 'Kibana', 'kibana', 'データ可視化ツール', 0, true, 29),
(UUID(), 'tools', 'fluentd', 'Fluentd', 'fluentd', 'ログ収集ツール', 0, true, 30),
(UUID(), 'tools', 'jira', 'JIRA', 'jira', 'プロジェクト管理ツール', 0, true, 31),
(UUID(), 'tools', 'confluence', 'Confluence', 'confluence', 'Wiki・ドキュメント管理', 0, true, 32),
(UUID(), 'tools', 'slack', 'Slack', 'slack', 'チャットツール', 0, true, 33),
(UUID(), 'tools', 'teams', 'Microsoft Teams', 'teams,ms teams', 'チャットツール', 0, true, 34),
(UUID(), 'tools', 'discord', 'Discord', 'discord', 'チャットツール', 0, true, 35),
(UUID(), 'tools', 'zoom', 'Zoom', 'zoom', 'ビデオ会議ツール', 0, true, 36),
(UUID(), 'tools', 'vscode', 'Visual Studio Code', 'vscode,vs code', 'コードエディタ', 0, true, 37),
(UUID(), 'tools', 'intellij', 'IntelliJ IDEA', 'intellij,idea', 'IDE', 0, true, 38),
(UUID(), 'tools', 'eclipse', 'Eclipse', 'eclipse', 'IDE', 0, true, 39),
(UUID(), 'tools', 'visualstudio', 'Visual Studio', 'vs,visual studio', 'IDE', 0, true, 40),
(UUID(), 'tools', 'xcode', 'Xcode', 'xcode', 'Apple IDE', 0, true, 41),
(UUID(), 'tools', 'androidstudio', 'Android Studio', 'android studio', 'Android IDE', 0, true, 42),
(UUID(), 'tools', 'sublime', 'Sublime Text', 'sublime,sublime text', 'テキストエディタ', 0, true, 43),
(UUID(), 'tools', 'atom', 'Atom', 'atom', 'テキストエディタ', 0, true, 44),
(UUID(), 'tools', 'vim', 'Vim', 'vim,vi', 'テキストエディタ', 0, true, 45),
(UUID(), 'tools', 'emacs', 'Emacs', 'emacs', 'テキストエディタ', 0, true, 46),
(UUID(), 'tools', 'notepad++', 'Notepad++', 'notepad++', 'テキストエディタ', 0, true, 47),
(UUID(), 'tools', 'postman', 'Postman', 'postman', 'APIテストツール', 0, true, 48),
(UUID(), 'tools', 'insomnia', 'Insomnia', 'insomnia', 'APIテストツール', 0, true, 49),
(UUID(), 'tools', 'soapui', 'SoapUI', 'soapui', 'APIテストツール', 0, true, 50),
(UUID(), 'tools', 'swagger', 'Swagger', 'swagger,openapi', 'API仕様ツール', 0, true, 51),
(UUID(), 'tools', 'maven', 'Maven', 'maven,mvn', 'ビルドツール', 0, true, 52),
(UUID(), 'tools', 'gradle', 'Gradle', 'gradle', 'ビルドツール', 0, true, 53),
(UUID(), 'tools', 'ant', 'Apache Ant', 'ant', 'ビルドツール', 0, true, 54),
(UUID(), 'tools', 'npm', 'npm', 'npm', 'パッケージマネージャー', 0, true, 55),
(UUID(), 'tools', 'yarn', 'Yarn', 'yarn', 'パッケージマネージャー', 0, true, 56),
(UUID(), 'tools', 'pnpm', 'pnpm', 'pnpm', 'パッケージマネージャー', 0, true, 57),
(UUID(), 'tools', 'pip', 'pip', 'pip', 'Pythonパッケージマネージャー', 0, true, 58),
(UUID(), 'tools', 'composer', 'Composer', 'composer', 'PHPパッケージマネージャー', 0, true, 59),
(UUID(), 'tools', 'bundler', 'Bundler', 'bundler', 'Rubyパッケージマネージャー', 0, true, 60),
(UUID(), 'tools', 'cargo', 'Cargo', 'cargo', 'Rustパッケージマネージャー', 0, true, 61),
(UUID(), 'tools', 'nuget', 'NuGet', 'nuget', '.NETパッケージマネージャー', 0, true, 62),
(UUID(), 'tools', 'homebrew', 'Homebrew', 'brew,homebrew', 'macOSパッケージマネージャー', 0, true, 63),
(UUID(), 'tools', 'chocolatey', 'Chocolatey', 'choco,chocolatey', 'Windowsパッケージマネージャー', 0, true, 64),
(UUID(), 'tools', 'webpack', 'Webpack', 'webpack', 'モジュールバンドラー', 0, true, 65),
(UUID(), 'tools', 'rollup', 'Rollup', 'rollup', 'モジュールバンドラー', 0, true, 66),
(UUID(), 'tools', 'parcel', 'Parcel', 'parcel', 'ビルドツール', 0, true, 67),
(UUID(), 'tools', 'vite', 'Vite', 'vite', 'ビルドツール', 0, true, 68),
(UUID(), 'tools', 'esbuild', 'esbuild', 'esbuild', 'ビルドツール', 0, true, 69),
(UUID(), 'tools', 'babel', 'Babel', 'babel', 'JavaScriptコンパイラ', 0, true, 70),
(UUID(), 'tools', 'typescript', 'TypeScript Compiler', 'tsc,typescript', 'TypeScriptコンパイラ', 0, true, 71),
(UUID(), 'tools', 'eslint', 'ESLint', 'eslint', 'JavaScriptリンター', 0, true, 72),
(UUID(), 'tools', 'prettier', 'Prettier', 'prettier', 'コードフォーマッター', 0, true, 73),
(UUID(), 'tools', 'jest', 'Jest', 'jest', 'テストフレームワーク', 0, true, 74),
(UUID(), 'tools', 'mocha', 'Mocha', 'mocha', 'テストフレームワーク', 0, true, 75),
(UUID(), 'tools', 'jasmine', 'Jasmine', 'jasmine', 'テストフレームワーク', 0, true, 76),
(UUID(), 'tools', 'cypress', 'Cypress', 'cypress', 'E2Eテストツール', 0, true, 77),
(UUID(), 'tools', 'selenium', 'Selenium', 'selenium', 'ブラウザ自動化ツール', 0, true, 78),
(UUID(), 'tools', 'playwright', 'Playwright', 'playwright', 'ブラウザ自動化ツール', 0, true, 79),
(UUID(), 'tools', 'puppeteer', 'Puppeteer', 'puppeteer', 'ブラウザ自動化ツール', 0, true, 80),
(UUID(), 'tools', 'junit', 'JUnit', 'junit', 'Javaテストフレームワーク', 0, true, 81),
(UUID(), 'tools', 'testng', 'TestNG', 'testng', 'Javaテストフレームワーク', 0, true, 82),
(UUID(), 'tools', 'pytest', 'pytest', 'pytest', 'Pythonテストフレームワーク', 0, true, 83),
(UUID(), 'tools', 'unittest', 'unittest', 'unittest', 'Pythonテストフレームワーク', 0, true, 84),
(UUID(), 'tools', 'rspec', 'RSpec', 'rspec', 'Rubyテストフレームワーク', 0, true, 85),
(UUID(), 'tools', 'phpunit', 'PHPUnit', 'phpunit', 'PHPテストフレームワーク', 0, true, 86),
(UUID(), 'tools', 'nunit', 'NUnit', 'nunit', '.NETテストフレームワーク', 0, true, 87),
(UUID(), 'tools', 'xunit', 'xUnit', 'xunit', '.NETテストフレームワーク', 0, true, 88),
(UUID(), 'tools', 'sonarqube', 'SonarQube', 'sonar,sonarqube', 'コード品質ツール', 0, true, 89),
(UUID(), 'tools', 'codecov', 'Codecov', 'codecov', 'コードカバレッジツール', 0, true, 90),
(UUID(), 'tools', 'coveralls', 'Coveralls', 'coveralls', 'コードカバレッジツール', 0, true, 91),
(UUID(), 'tools', 'sentry', 'Sentry', 'sentry', 'エラー監視ツール', 0, true, 92),
(UUID(), 'tools', 'rollbar', 'Rollbar', 'rollbar', 'エラー監視ツール', 0, true, 93),
(UUID(), 'tools', 'bugsnag', 'Bugsnag', 'bugsnag', 'エラー監視ツール', 0, true, 94),
(UUID(), 'tools', 'airbrake', 'Airbrake', 'airbrake', 'エラー監視ツール', 0, true, 95),
(UUID(), 'tools', 'lighthouse', 'Lighthouse', 'lighthouse', 'Webパフォーマンスツール', 0, true, 96),
(UUID(), 'tools', 'gtmetrix', 'GTmetrix', 'gtmetrix', 'Webパフォーマンスツール', 0, true, 97),
(UUID(), 'tools', 'pagespeed', 'PageSpeed Insights', 'pagespeed', 'Webパフォーマンスツール', 0, true, 98),
(UUID(), 'tools', 'webpagetest', 'WebPageTest', 'webpagetest', 'Webパフォーマンスツール', 0, true, 99),
(UUID(), 'tools', 'figma', 'Figma', 'figma', 'デザインツール', 0, true, 100);