CREATE TABLE change_histories (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    user_id CHAR(36) NOT NULL,
    target_type VARCHAR(50) NOT NULL COMMENT '変更対象の種類(user, engineer, project等)',
    target_id CHAR(36) NOT NULL COMMENT '変更対象のID',
    field_name VARCHAR(100) NOT NULL COMMENT '変更されたフィールド名',
    field_label VARCHAR(100) NOT NULL COMMENT 'フィールドの日本語名',
    old_value TEXT COMMENT '変更前の値',
    new_value TEXT COMMENT '変更後の値',
    change_type ENUM('create', 'update', 'delete') NOT NULL DEFAULT 'update',
    reason TEXT COMMENT '変更理由',
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_target (target_type, target_id),
    INDEX idx_field_name (field_name),
    INDEX idx_change_type (change_type),
    INDEX idx_created_at (created_at),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;