-- 経費申請上限テーブルのスコープ機能を削除 -- 1. 外部キー制約を削除 ALTER TABLE expense_limits DROP FOREIGN KEY IF EXISTS fk_expense_limits_user_id;
-- ALTER TABLE expense_limits DROP FOREIGN KEY IF EXISTS fk_expense_limits_department_id;
-- 2. インデックスを削除 ALTER TABLE expense_limits DROP INDEX IF EXISTS idx_expense_limits_dept_type_effective;
ALTER TABLE expense_limits DROP INDEX IF EXISTS idx_expense_limits_user_type_effective;
ALTER TABLE expense_limits DROP INDEX IF EXISTS idx_expense_limits_scope_type_effective;
ALTER TABLE expense_limits DROP INDEX IF EXISTS idx_expense_limits_department_id;
ALTER TABLE expense_limits DROP INDEX IF EXISTS idx_expense_limits_user_id;
-- 3. 追加された列を削除 ALTER TABLE expense_limits DROP COLUMN IF EXISTS department_id;
ALTER TABLE expense_limits DROP COLUMN IF EXISTS user_id;
ALTER TABLE expense_limits DROP COLUMN IF EXISTS limit_scope;
