-- 技術マスタのシードデータ投入（PostgreSQL版）

-- プログラミング言語 (programming_languages)
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES 
(gen_random_uuid(), 'programming_languages', 'java', 'Java', 'java', 'オブジェクト指向プログラミング言語', 0, true, 1),
(gen_random_uuid(), 'programming_languages', 'javascript', 'JavaScript', 'js,javascript,ES6,ES2015', 'Web開発用スクリプト言語', 0, true, 2),
(gen_random_uuid(), 'programming_languages', 'typescript', 'TypeScript', 'ts,typescript', 'JavaScriptの型付きスーパーセット', 0, true, 3),
(gen_random_uuid(), 'programming_languages', 'python', 'Python', 'python,py', '汎用高水準プログラミング言語', 0, true, 4),
(gen_random_uuid(), 'programming_languages', 'go', 'Go', 'golang,go', 'Google開発のプログラミング言語', 0, true, 5),
(gen_random_uuid(), 'programming_languages', 'csharp', 'C#', 'c#,cs,csharp', 'Microsoft開発のオブジェクト指向言語', 0, true, 6),
(gen_random_uuid(), 'programming_languages', 'php', 'PHP', 'php', 'サーバーサイドスクリプト言語', 0, true, 7),
(gen_random_uuid(), 'programming_languages', 'ruby', 'Ruby', 'ruby,rb', 'オブジェクト指向スクリプト言語', 0, true, 8),
(gen_random_uuid(), 'programming_languages', 'swift', 'Swift', 'swift', 'Apple開発のプログラミング言語', 0, true, 9),
(gen_random_uuid(), 'programming_languages', 'kotlin', 'Kotlin', 'kotlin,kt', 'JVM上で動作する静的型付け言語', 0, true, 10),
(gen_random_uuid(), 'programming_languages', 'rust', 'Rust', 'rust,rs', 'システムプログラミング言語', 0, true, 11),
(gen_random_uuid(), 'programming_languages', 'cplusplus', 'C++', 'c++,cpp,cxx', 'オブジェクト指向プログラミング言語', 0, true, 12),
(gen_random_uuid(), 'programming_languages', 'c', 'C', 'c', 'システムプログラミング言語', 0, true, 13),
(gen_random_uuid(), 'programming_languages', 'scala', 'Scala', 'scala', 'JVM上で動作する関数型言語', 0, true, 14),
(gen_random_uuid(), 'programming_languages', 'dart', 'Dart', 'dart', 'Google開発のプログラミング言語', 0, true, 15),
(gen_random_uuid(), 'programming_languages', 'r', 'R', 'r,rlang', '統計解析向けプログラミング言語', 0, true, 16),
(gen_random_uuid(), 'programming_languages', 'matlab', 'MATLAB', 'matlab', '数値計算プログラミング言語', 0, true, 17),
(gen_random_uuid(), 'programming_languages', 'perl', 'Perl', 'perl,pl', 'テキスト処理に優れた言語', 0, true, 18),
(gen_random_uuid(), 'programming_languages', 'elixir', 'Elixir', 'elixir,ex', 'Erlang VM上で動作する関数型言語', 0, true, 19),
(gen_random_uuid(), 'programming_languages', 'clojure', 'Clojure', 'clojure,clj', 'JVM上で動作するLisp系言語', 0, true, 20),
(gen_random_uuid(), 'programming_languages', 'haskell', 'Haskell', 'haskell,hs', '純粋関数型プログラミング言語', 0, true, 21),
(gen_random_uuid(), 'programming_languages', 'lua', 'Lua', 'lua', '軽量スクリプト言語', 0, true, 22),
(gen_random_uuid(), 'programming_languages', 'julia', 'Julia', 'julia,jl', '科学技術計算向け言語', 0, true, 23),
(gen_random_uuid(), 'programming_languages', 'groovy', 'Groovy', 'groovy', 'JVM上で動作する動的言語', 0, true, 24),
(gen_random_uuid(), 'programming_languages', 'objective-c', 'Objective-C', 'objc,objective-c', 'Apple製品開発言語', 0, true, 25),
(gen_random_uuid(), 'programming_languages', 'vb.net', 'VB.NET', 'vb,vb.net,visualbasic', 'Visual Basic .NET', 0, true, 26),
(gen_random_uuid(), 'programming_languages', 'fsharp', 'F#', 'f#,fsharp,fs', '.NET向け関数型言語', 0, true, 27),
(gen_random_uuid(), 'programming_languages', 'erlang', 'Erlang', 'erlang,erl', '並行処理向け関数型言語', 0, true, 28),
(gen_random_uuid(), 'programming_languages', 'shell', 'Shell Script', 'shell,bash,sh,zsh', 'シェルスクリプト', 0, true, 29),
(gen_random_uuid(), 'programming_languages', 'powershell', 'PowerShell', 'powershell,ps1', 'Windows向けシェル', 0, true, 30)
ON CONFLICT DO NOTHING;

-- サーバー・データベース (servers_databases)
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES 
(gen_random_uuid(), 'servers_databases', 'mysql', 'MySQL', 'mysql', 'オープンソースRDBMS', 0, true, 1),
(gen_random_uuid(), 'servers_databases', 'postgresql', 'PostgreSQL', 'postgres,postgresql,pg', 'オープンソースRDBMS', 0, true, 2),
(gen_random_uuid(), 'servers_databases', 'mariadb', 'MariaDB', 'mariadb', 'MySQLフォーク', 0, true, 3),
(gen_random_uuid(), 'servers_databases', 'oracle', 'Oracle Database', 'oracle,oracledb', '商用RDBMS', 0, true, 4),
(gen_random_uuid(), 'servers_databases', 'sqlserver', 'SQL Server', 'mssql,sqlserver,sql server', 'Microsoft RDBMS', 0, true, 5),
(gen_random_uuid(), 'servers_databases', 'mongodb', 'MongoDB', 'mongo,mongodb', 'ドキュメント指向DB', 0, true, 6),
(gen_random_uuid(), 'servers_databases', 'redis', 'Redis', 'redis', 'インメモリDB', 0, true, 7),
(gen_random_uuid(), 'servers_databases', 'elasticsearch', 'Elasticsearch', 'elasticsearch,es', '全文検索エンジン', 0, true, 8),
(gen_random_uuid(), 'servers_databases', 'cassandra', 'Apache Cassandra', 'cassandra', '分散型NoSQL', 0, true, 9),
(gen_random_uuid(), 'servers_databases', 'dynamodb', 'Amazon DynamoDB', 'dynamodb', 'AWS NoSQL', 0, true, 10),
(gen_random_uuid(), 'servers_databases', 'firebase', 'Firebase', 'firebase', 'Google BaaS', 0, true, 11),
(gen_random_uuid(), 'servers_databases', 'couchdb', 'CouchDB', 'couchdb', 'ドキュメント指向DB', 0, true, 12),
(gen_random_uuid(), 'servers_databases', 'neo4j', 'Neo4j', 'neo4j', 'グラフDB', 0, true, 13),
(gen_random_uuid(), 'servers_databases', 'influxdb', 'InfluxDB', 'influxdb', '時系列DB', 0, true, 14),
(gen_random_uuid(), 'servers_databases', 'memcached', 'Memcached', 'memcached', 'キャッシュサーバー', 0, true, 15),
(gen_random_uuid(), 'servers_databases', 'apache', 'Apache HTTP Server', 'apache,httpd', 'Webサーバー', 0, true, 21),
(gen_random_uuid(), 'servers_databases', 'nginx', 'Nginx', 'nginx', 'Webサーバー', 0, true, 22),
(gen_random_uuid(), 'servers_databases', 'iis', 'IIS', 'iis', 'Microsoft Webサーバー', 0, true, 23),
(gen_random_uuid(), 'servers_databases', 'tomcat', 'Apache Tomcat', 'tomcat', 'Javaサーブレットコンテナ', 0, true, 24),
(gen_random_uuid(), 'servers_databases', 'nodejs', 'Node.js', 'node,nodejs,node.js', 'JavaScript実行環境', 0, true, 30)
ON CONFLICT DO NOTHING;

-- ツール (tools)
INSERT INTO technology_master (id, category, name, display_name, aliases, description, usage_count, is_active, sort_order) VALUES 
(gen_random_uuid(), 'tools', 'git', 'Git', 'git', 'バージョン管理システム', 0, true, 1),
(gen_random_uuid(), 'tools', 'svn', 'Subversion', 'svn,subversion', 'バージョン管理システム', 0, true, 2),
(gen_random_uuid(), 'tools', 'mercurial', 'Mercurial', 'hg,mercurial', 'バージョン管理システム', 0, true, 3),
(gen_random_uuid(), 'tools', 'docker', 'Docker', 'docker', 'コンテナプラットフォーム', 0, true, 4),
(gen_random_uuid(), 'tools', 'kubernetes', 'Kubernetes', 'k8s,kubernetes', 'コンテナオーケストレーション', 0, true, 5),
(gen_random_uuid(), 'tools', 'jenkins', 'Jenkins', 'jenkins', 'CI/CDツール', 0, true, 6),
(gen_random_uuid(), 'tools', 'gitlab', 'GitLab', 'gitlab', 'DevOpsプラットフォーム', 0, true, 7),
(gen_random_uuid(), 'tools', 'github', 'GitHub', 'github', 'コード共有プラットフォーム', 0, true, 8),
(gen_random_uuid(), 'tools', 'bitbucket', 'Bitbucket', 'bitbucket', 'Gitリポジトリ管理', 0, true, 9),
(gen_random_uuid(), 'tools', 'circleci', 'CircleCI', 'circleci', 'CI/CDツール', 0, true, 10),
(gen_random_uuid(), 'tools', 'ansible', 'Ansible', 'ansible', '構成管理ツール', 0, true, 13),
(gen_random_uuid(), 'tools', 'terraform', 'Terraform', 'terraform', 'IaCツール', 0, true, 14),
(gen_random_uuid(), 'tools', 'prometheus', 'Prometheus', 'prometheus', '監視システム', 0, true, 20),
(gen_random_uuid(), 'tools', 'grafana', 'Grafana', 'grafana', '可視化ツール', 0, true, 21),
(gen_random_uuid(), 'tools', 'jira', 'JIRA', 'jira', 'プロジェクト管理ツール', 0, true, 31),
(gen_random_uuid(), 'tools', 'confluence', 'Confluence', 'confluence', 'Wiki・ドキュメント管理', 0, true, 32),
(gen_random_uuid(), 'tools', 'slack', 'Slack', 'slack', 'チャットツール', 0, true, 33),
(gen_random_uuid(), 'tools', 'teams', 'Microsoft Teams', 'teams,ms teams', 'チャットツール', 0, true, 34),
(gen_random_uuid(), 'tools', 'vscode', 'Visual Studio Code', 'vscode,vs code', 'コードエディタ', 0, true, 37),
(gen_random_uuid(), 'tools', 'intellij', 'IntelliJ IDEA', 'intellij,idea', 'IDE', 0, true, 38),
(gen_random_uuid(), 'tools', 'eclipse', 'Eclipse', 'eclipse', 'IDE', 0, true, 39),
(gen_random_uuid(), 'tools', 'visualstudio', 'Visual Studio', 'vs,visual studio', 'IDE', 0, true, 40),
(gen_random_uuid(), 'tools', 'postman', 'Postman', 'postman', 'APIテストツール', 0, true, 48),
(gen_random_uuid(), 'tools', 'swagger', 'Swagger', 'swagger,openapi', 'API仕様ツール', 0, true, 51),
(gen_random_uuid(), 'tools', 'maven', 'Maven', 'maven,mvn', 'ビルドツール', 0, true, 52),
(gen_random_uuid(), 'tools', 'gradle', 'Gradle', 'gradle', 'ビルドツール', 0, true, 53),
(gen_random_uuid(), 'tools', 'npm', 'npm', 'npm', 'パッケージマネージャー', 0, true, 55),
(gen_random_uuid(), 'tools', 'yarn', 'Yarn', 'yarn', 'パッケージマネージャー', 0, true, 56),
(gen_random_uuid(), 'tools', 'webpack', 'Webpack', 'webpack', 'モジュールバンドラー', 0, true, 65),
(gen_random_uuid(), 'tools', 'jest', 'Jest', 'jest', 'テストフレームワーク', 0, true, 74),
(gen_random_uuid(), 'tools', 'selenium', 'Selenium', 'selenium', 'ブラウザ自動化ツール', 0, true, 78),
(gen_random_uuid(), 'tools', 'junit', 'JUnit', 'junit', 'Javaテストフレームワーク', 0, true, 81),
(gen_random_uuid(), 'tools', 'pytest', 'pytest', 'pytest', 'Pythonテストフレームワーク', 0, true, 83),
(gen_random_uuid(), 'tools', 'rspec', 'RSpec', 'rspec', 'Rubyテストフレームワーク', 0, true, 85),
(gen_random_uuid(), 'tools', 'phpunit', 'PHPUnit', 'phpunit', 'PHPテストフレームワーク', 0, true, 86),
(gen_random_uuid(), 'tools', 'sonarqube', 'SonarQube', 'sonar,sonarqube', 'コード品質ツール', 0, true, 89),
(gen_random_uuid(), 'tools', 'figma', 'Figma', 'figma', 'デザインツール', 0, true, 100)
ON CONFLICT DO NOTHING;