-- パフォーマンスインデックスの削除 -- users テーブルのインデックス削除 DROP INDEX IF EXISTS idx_users_role_status;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_employee_number;
DROP INDEX IF EXISTS idx_users_department_status;
DROP INDEX IF EXISTS idx_users_search;
-- engineer_status_history テーブルのインデックス削除 DROP INDEX IF EXISTS idx_engineer_status_history_user_changed;
DROP INDEX IF EXISTS idx_engineer_status_history_status;
-- engineer_skills テーブルのインデックス削除 DROP INDEX IF EXISTS idx_engineer_skills_user_category;
DROP INDEX IF EXISTS idx_engineer_skills_category;
DROP INDEX IF EXISTS idx_engineer_skills_level;
-- engineer_project_history テーブルのインデックス削除 DROP INDEX IF EXISTS idx_engineer_project_history_user_date;
DROP INDEX IF EXISTS idx_engineer_project_history_project;
DROP INDEX IF EXISTS idx_engineer_project_history_period;
-- audit_logs テーブルのインデックス削除 DROP INDEX IF EXISTS idx_audit_logs_user_created;
DROP INDEX IF EXISTS idx_audit_logs_resource_created;
-- change_histories テーブルのインデックス削除 DROP INDEX IF EXISTS idx_change_histories_user_created;
DROP INDEX IF EXISTS idx_change_histories_target_created;
