-- 週報テーブルのインデックス最適化 -- P0-T3のデータベース最適化計画書に基づく -- 1. ユーザー別週報検索（最頻出クエリ） CREATE INDEX idx_weekly_reports_user_date ON weekly_reports(user_id, start_date DESC);
-- 2. ステータス別検索の最適化 CREATE INDEX idx_weekly_reports_status_created ON weekly_reports(status, created_at DESC);
-- 3. 日付範囲検索の最適化 CREATE INDEX idx_weekly_reports_date_range ON weekly_reports(start_date, end_date);
-- 4. 削除済みを除外した検索の最適化 CREATE INDEX idx_weekly_reports_deleted_status ON weekly_reports(deleted_at, status);
-- 5. 提出日での検索最適化 CREATE INDEX idx_weekly_reports_submitted_at ON weekly_reports(submitted_at);
-- 6. カバリングインデックス（頻出カラムを含む） CREATE INDEX idx_weekly_reports_covering ON weekly_reports( user_id, status, start_date, end_date, total_work_hours, submitted_at );
-- 7. 未提出者検索の最適化（週報管理機能で重要） CREATE INDEX idx_weekly_reports_unsubmitted ON weekly_reports( user_id, end_date, status, deleted_at );
-- 8. フルテキスト検索インデックス（MySQL 5.7以降） -- 週報のコメント等の検索用 ALTER TABLE weekly_reports ADD FULLTEXT idx_weekly_reports_fulltext (weekly_remarks);
-- 9. 月次集計用インデックス（管理者画面で頻用） CREATE INDEX idx_weekly_reports_monthly ON weekly_reports( YEAR(start_date), MONTH(start_date), status, deleted_at );
