name: E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Start services (Docker Compose)
        run: |
          docker compose up -d
          docker compose ps

      - name: Wait for backend (8080) and frontend (3000)
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:8080/health >/dev/null; then echo "Backend OK"; break; fi; sleep 2; done
          for i in {1..60}; do
            if curl -sSf http://localhost:3000 >/dev/null; then echo "Frontend OK"; break; fi; sleep 2; done

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests (chromium)
        working-directory: frontend
        env:
          E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          E2E_ADMIN_EMAIL: ${{ secrets.E2E_ADMIN_EMAIL }}
          E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          E2E_BASE_URL: http://localhost:3000
        run: |
          npx playwright test --grep "@smoke" --config=playwright.ci.config.ts --project=chromium

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            frontend/test-results
            frontend/playwright-report
          if-no-files-found: ignore
